language: generic 

sudo: required
services:
  - docker

before-install:
  - docker build -t froliceric/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true froliceric/docker-react npm run test